# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 0.8.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetCharactersNames200Ok(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'character_id': 'int',
        'character_name': 'str'
    }

    attribute_map = {
        'character_id': 'character_id',
        'character_name': 'character_name'
    }

    def __init__(self, character_id=None, character_name=None):  # noqa: E501
        """GetCharactersNames200Ok - a model defined in Swagger"""  # noqa: E501

        self._character_id = None
        self._character_name = None
        self.discriminator = None

        self.character_id = character_id
        self.character_name = character_name

    @property
    def character_id(self):
        """Gets the character_id of this GetCharactersNames200Ok.  # noqa: E501

        character_id integer  # noqa: E501

        :return: The character_id of this GetCharactersNames200Ok.  # noqa: E501
        :rtype: int
        """
        return self._character_id

    @character_id.setter
    def character_id(self, character_id):
        """Sets the character_id of this GetCharactersNames200Ok.

        character_id integer  # noqa: E501

        :param character_id: The character_id of this GetCharactersNames200Ok.  # noqa: E501
        :type: int
        """
        if character_id is None:
            raise ValueError("Invalid value for `character_id`, must not be `None`")  # noqa: E501

        self._character_id = character_id

    @property
    def character_name(self):
        """Gets the character_name of this GetCharactersNames200Ok.  # noqa: E501

        character_name string  # noqa: E501

        :return: The character_name of this GetCharactersNames200Ok.  # noqa: E501
        :rtype: str
        """
        return self._character_name

    @character_name.setter
    def character_name(self, character_name):
        """Sets the character_name of this GetCharactersNames200Ok.

        character_name string  # noqa: E501

        :param character_name: The character_name of this GetCharactersNames200Ok.  # noqa: E501
        :type: str
        """
        if character_name is None:
            raise ValueError("Invalid value for `character_name`, must not be `None`")  # noqa: E501

        self._character_name = character_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCharactersNames200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
