# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 0.8.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetCharactersCharacterIdWalletJournalExtraInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location_id': 'int',
        'transaction_id': 'int',
        'npc_name': 'str',
        'npc_id': 'int',
        'destroyed_ship_type_id': 'int',
        'character_id': 'int',
        'corporation_id': 'int',
        'alliance_id': 'int',
        'job_id': 'int',
        'contract_id': 'int',
        'system_id': 'int',
        'planet_id': 'int'
    }

    attribute_map = {
        'location_id': 'location_id',
        'transaction_id': 'transaction_id',
        'npc_name': 'npc_name',
        'npc_id': 'npc_id',
        'destroyed_ship_type_id': 'destroyed_ship_type_id',
        'character_id': 'character_id',
        'corporation_id': 'corporation_id',
        'alliance_id': 'alliance_id',
        'job_id': 'job_id',
        'contract_id': 'contract_id',
        'system_id': 'system_id',
        'planet_id': 'planet_id'
    }

    def __init__(self, location_id=None, transaction_id=None, npc_name=None, npc_id=None, destroyed_ship_type_id=None, character_id=None, corporation_id=None, alliance_id=None, job_id=None, contract_id=None, system_id=None, planet_id=None):  # noqa: E501
        """GetCharactersCharacterIdWalletJournalExtraInfo - a model defined in Swagger"""  # noqa: E501

        self._location_id = None
        self._transaction_id = None
        self._npc_name = None
        self._npc_id = None
        self._destroyed_ship_type_id = None
        self._character_id = None
        self._corporation_id = None
        self._alliance_id = None
        self._job_id = None
        self._contract_id = None
        self._system_id = None
        self._planet_id = None
        self.discriminator = None

        if location_id is not None:
            self.location_id = location_id
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if npc_name is not None:
            self.npc_name = npc_name
        if npc_id is not None:
            self.npc_id = npc_id
        if destroyed_ship_type_id is not None:
            self.destroyed_ship_type_id = destroyed_ship_type_id
        if character_id is not None:
            self.character_id = character_id
        if corporation_id is not None:
            self.corporation_id = corporation_id
        if alliance_id is not None:
            self.alliance_id = alliance_id
        if job_id is not None:
            self.job_id = job_id
        if contract_id is not None:
            self.contract_id = contract_id
        if system_id is not None:
            self.system_id = system_id
        if planet_id is not None:
            self.planet_id = planet_id

    @property
    def location_id(self):
        """Gets the location_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        location_id integer  # noqa: E501

        :return: The location_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        location_id integer  # noqa: E501

        :param location_id: The location_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._location_id = location_id

    @property
    def transaction_id(self):
        """Gets the transaction_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        transaction_id integer  # noqa: E501

        :return: The transaction_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        transaction_id integer  # noqa: E501

        :param transaction_id: The transaction_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._transaction_id = transaction_id

    @property
    def npc_name(self):
        """Gets the npc_name of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        npc_name string  # noqa: E501

        :return: The npc_name of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: str
        """
        return self._npc_name

    @npc_name.setter
    def npc_name(self, npc_name):
        """Sets the npc_name of this GetCharactersCharacterIdWalletJournalExtraInfo.

        npc_name string  # noqa: E501

        :param npc_name: The npc_name of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: str
        """

        self._npc_name = npc_name

    @property
    def npc_id(self):
        """Gets the npc_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        npc_id integer  # noqa: E501

        :return: The npc_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._npc_id

    @npc_id.setter
    def npc_id(self, npc_id):
        """Sets the npc_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        npc_id integer  # noqa: E501

        :param npc_id: The npc_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._npc_id = npc_id

    @property
    def destroyed_ship_type_id(self):
        """Gets the destroyed_ship_type_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        destroyed_ship_type_id integer  # noqa: E501

        :return: The destroyed_ship_type_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._destroyed_ship_type_id

    @destroyed_ship_type_id.setter
    def destroyed_ship_type_id(self, destroyed_ship_type_id):
        """Sets the destroyed_ship_type_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        destroyed_ship_type_id integer  # noqa: E501

        :param destroyed_ship_type_id: The destroyed_ship_type_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._destroyed_ship_type_id = destroyed_ship_type_id

    @property
    def character_id(self):
        """Gets the character_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        character_id integer  # noqa: E501

        :return: The character_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._character_id

    @character_id.setter
    def character_id(self, character_id):
        """Sets the character_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        character_id integer  # noqa: E501

        :param character_id: The character_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._character_id = character_id

    @property
    def corporation_id(self):
        """Gets the corporation_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        corporation_id integer  # noqa: E501

        :return: The corporation_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._corporation_id

    @corporation_id.setter
    def corporation_id(self, corporation_id):
        """Sets the corporation_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        corporation_id integer  # noqa: E501

        :param corporation_id: The corporation_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._corporation_id = corporation_id

    @property
    def alliance_id(self):
        """Gets the alliance_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        alliance_id integer  # noqa: E501

        :return: The alliance_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._alliance_id

    @alliance_id.setter
    def alliance_id(self, alliance_id):
        """Sets the alliance_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        alliance_id integer  # noqa: E501

        :param alliance_id: The alliance_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._alliance_id = alliance_id

    @property
    def job_id(self):
        """Gets the job_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        job_id integer  # noqa: E501

        :return: The job_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        job_id integer  # noqa: E501

        :param job_id: The job_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def contract_id(self):
        """Gets the contract_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        contract_id integer  # noqa: E501

        :return: The contract_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._contract_id

    @contract_id.setter
    def contract_id(self, contract_id):
        """Sets the contract_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        contract_id integer  # noqa: E501

        :param contract_id: The contract_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._contract_id = contract_id

    @property
    def system_id(self):
        """Gets the system_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        system_id integer  # noqa: E501

        :return: The system_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._system_id

    @system_id.setter
    def system_id(self, system_id):
        """Sets the system_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        system_id integer  # noqa: E501

        :param system_id: The system_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._system_id = system_id

    @property
    def planet_id(self):
        """Gets the planet_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501

        planet_id integer  # noqa: E501

        :return: The planet_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :rtype: int
        """
        return self._planet_id

    @planet_id.setter
    def planet_id(self, planet_id):
        """Sets the planet_id of this GetCharactersCharacterIdWalletJournalExtraInfo.

        planet_id integer  # noqa: E501

        :param planet_id: The planet_id of this GetCharactersCharacterIdWalletJournalExtraInfo.  # noqa: E501
        :type: int
        """

        self._planet_id = planet_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCharactersCharacterIdWalletJournalExtraInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
