# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 0.8.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetCharactersCharacterIdOrdersHistory200Ok(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_id': 'int',
        'type_id': 'int',
        'region_id': 'int',
        'location_id': 'int',
        'range': 'str',
        'price': 'float',
        'volume_total': 'int',
        'volume_remain': 'int',
        'issued': 'datetime',
        'is_buy_order': 'bool',
        'min_volume': 'int',
        'escrow': 'float',
        'duration': 'int',
        'state': 'str',
        'is_corporation': 'bool'
    }

    attribute_map = {
        'order_id': 'order_id',
        'type_id': 'type_id',
        'region_id': 'region_id',
        'location_id': 'location_id',
        'range': 'range',
        'price': 'price',
        'volume_total': 'volume_total',
        'volume_remain': 'volume_remain',
        'issued': 'issued',
        'is_buy_order': 'is_buy_order',
        'min_volume': 'min_volume',
        'escrow': 'escrow',
        'duration': 'duration',
        'state': 'state',
        'is_corporation': 'is_corporation'
    }

    def __init__(self, order_id=None, type_id=None, region_id=None, location_id=None, range=None, price=None, volume_total=None, volume_remain=None, issued=None, is_buy_order=None, min_volume=None, escrow=None, duration=None, state=None, is_corporation=None):  # noqa: E501
        """GetCharactersCharacterIdOrdersHistory200Ok - a model defined in Swagger"""  # noqa: E501

        self._order_id = None
        self._type_id = None
        self._region_id = None
        self._location_id = None
        self._range = None
        self._price = None
        self._volume_total = None
        self._volume_remain = None
        self._issued = None
        self._is_buy_order = None
        self._min_volume = None
        self._escrow = None
        self._duration = None
        self._state = None
        self._is_corporation = None
        self.discriminator = None

        self.order_id = order_id
        self.type_id = type_id
        self.region_id = region_id
        self.location_id = location_id
        self.range = range
        self.price = price
        self.volume_total = volume_total
        self.volume_remain = volume_remain
        self.issued = issued
        if is_buy_order is not None:
            self.is_buy_order = is_buy_order
        if min_volume is not None:
            self.min_volume = min_volume
        if escrow is not None:
            self.escrow = escrow
        self.duration = duration
        self.state = state
        self.is_corporation = is_corporation

    @property
    def order_id(self):
        """Gets the order_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Unique order ID  # noqa: E501

        :return: The order_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this GetCharactersCharacterIdOrdersHistory200Ok.

        Unique order ID  # noqa: E501

        :param order_id: The order_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def type_id(self):
        """Gets the type_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        The type ID of the item transacted in this order  # noqa: E501

        :return: The type_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this GetCharactersCharacterIdOrdersHistory200Ok.

        The type ID of the item transacted in this order  # noqa: E501

        :param type_id: The type_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if type_id is None:
            raise ValueError("Invalid value for `type_id`, must not be `None`")  # noqa: E501

        self._type_id = type_id

    @property
    def region_id(self):
        """Gets the region_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        ID of the region where order was placed  # noqa: E501

        :return: The region_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this GetCharactersCharacterIdOrdersHistory200Ok.

        ID of the region where order was placed  # noqa: E501

        :param region_id: The region_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if region_id is None:
            raise ValueError("Invalid value for `region_id`, must not be `None`")  # noqa: E501

        self._region_id = region_id

    @property
    def location_id(self):
        """Gets the location_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        ID of the location where order was placed  # noqa: E501

        :return: The location_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this GetCharactersCharacterIdOrdersHistory200Ok.

        ID of the location where order was placed  # noqa: E501

        :param location_id: The location_id of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if location_id is None:
            raise ValueError("Invalid value for `location_id`, must not be `None`")  # noqa: E501

        self._location_id = location_id

    @property
    def range(self):
        """Gets the range of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Valid order range, numbers are ranges in jumps  # noqa: E501

        :return: The range of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: str
        """
        return self._range

    @range.setter
    def range(self, range):
        """Sets the range of this GetCharactersCharacterIdOrdersHistory200Ok.

        Valid order range, numbers are ranges in jumps  # noqa: E501

        :param range: The range of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: str
        """
        if range is None:
            raise ValueError("Invalid value for `range`, must not be `None`")  # noqa: E501
        allowed_values = ["1", "10", "2", "20", "3", "30", "4", "40", "5", "region", "solarsystem", "station"]  # noqa: E501
        if range not in allowed_values:
            raise ValueError(
                "Invalid value for `range` ({0}), must be one of {1}"  # noqa: E501
                .format(range, allowed_values)
            )

        self._range = range

    @property
    def price(self):
        """Gets the price of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Cost per unit for this order  # noqa: E501

        :return: The price of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this GetCharactersCharacterIdOrdersHistory200Ok.

        Cost per unit for this order  # noqa: E501

        :param price: The price of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def volume_total(self):
        """Gets the volume_total of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Quantity of items required or offered at time order was placed  # noqa: E501

        :return: The volume_total of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._volume_total

    @volume_total.setter
    def volume_total(self, volume_total):
        """Sets the volume_total of this GetCharactersCharacterIdOrdersHistory200Ok.

        Quantity of items required or offered at time order was placed  # noqa: E501

        :param volume_total: The volume_total of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if volume_total is None:
            raise ValueError("Invalid value for `volume_total`, must not be `None`")  # noqa: E501

        self._volume_total = volume_total

    @property
    def volume_remain(self):
        """Gets the volume_remain of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Quantity of items still required or offered  # noqa: E501

        :return: The volume_remain of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._volume_remain

    @volume_remain.setter
    def volume_remain(self, volume_remain):
        """Sets the volume_remain of this GetCharactersCharacterIdOrdersHistory200Ok.

        Quantity of items still required or offered  # noqa: E501

        :param volume_remain: The volume_remain of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if volume_remain is None:
            raise ValueError("Invalid value for `volume_remain`, must not be `None`")  # noqa: E501

        self._volume_remain = volume_remain

    @property
    def issued(self):
        """Gets the issued of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Date and time when this order was issued  # noqa: E501

        :return: The issued of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: datetime
        """
        return self._issued

    @issued.setter
    def issued(self, issued):
        """Sets the issued of this GetCharactersCharacterIdOrdersHistory200Ok.

        Date and time when this order was issued  # noqa: E501

        :param issued: The issued of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: datetime
        """
        if issued is None:
            raise ValueError("Invalid value for `issued`, must not be `None`")  # noqa: E501

        self._issued = issued

    @property
    def is_buy_order(self):
        """Gets the is_buy_order of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        True if the order is a bid (buy) order  # noqa: E501

        :return: The is_buy_order of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: bool
        """
        return self._is_buy_order

    @is_buy_order.setter
    def is_buy_order(self, is_buy_order):
        """Sets the is_buy_order of this GetCharactersCharacterIdOrdersHistory200Ok.

        True if the order is a bid (buy) order  # noqa: E501

        :param is_buy_order: The is_buy_order of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: bool
        """

        self._is_buy_order = is_buy_order

    @property
    def min_volume(self):
        """Gets the min_volume of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        For buy orders, the minimum quantity that will be accepted in a matching sell order  # noqa: E501

        :return: The min_volume of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._min_volume

    @min_volume.setter
    def min_volume(self, min_volume):
        """Sets the min_volume of this GetCharactersCharacterIdOrdersHistory200Ok.

        For buy orders, the minimum quantity that will be accepted in a matching sell order  # noqa: E501

        :param min_volume: The min_volume of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """

        self._min_volume = min_volume

    @property
    def escrow(self):
        """Gets the escrow of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        For buy orders, the amount of ISK in escrow  # noqa: E501

        :return: The escrow of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: float
        """
        return self._escrow

    @escrow.setter
    def escrow(self, escrow):
        """Sets the escrow of this GetCharactersCharacterIdOrdersHistory200Ok.

        For buy orders, the amount of ISK in escrow  # noqa: E501

        :param escrow: The escrow of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: float
        """

        self._escrow = escrow

    @property
    def duration(self):
        """Gets the duration of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Number of days the order was valid for (starting from the issued date). An order expires at time issued + duration  # noqa: E501

        :return: The duration of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this GetCharactersCharacterIdOrdersHistory200Ok.

        Number of days the order was valid for (starting from the issued date). An order expires at time issued + duration  # noqa: E501

        :param duration: The duration of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: int
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")  # noqa: E501

        self._duration = duration

    @property
    def state(self):
        """Gets the state of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Current order state  # noqa: E501

        :return: The state of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetCharactersCharacterIdOrdersHistory200Ok.

        Current order state  # noqa: E501

        :param state: The state of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501
        allowed_values = ["cancelled", "expired"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def is_corporation(self):
        """Gets the is_corporation of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501

        Signifies whether the buy/sell order was placed on behalf of a corporation.  # noqa: E501

        :return: The is_corporation of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :rtype: bool
        """
        return self._is_corporation

    @is_corporation.setter
    def is_corporation(self, is_corporation):
        """Sets the is_corporation of this GetCharactersCharacterIdOrdersHistory200Ok.

        Signifies whether the buy/sell order was placed on behalf of a corporation.  # noqa: E501

        :param is_corporation: The is_corporation of this GetCharactersCharacterIdOrdersHistory200Ok.  # noqa: E501
        :type: bool
        """
        if is_corporation is None:
            raise ValueError("Invalid value for `is_corporation`, must not be `None`")  # noqa: E501

        self._is_corporation = is_corporation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCharactersCharacterIdOrdersHistory200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
